/**
* Resources
* ---------
* This file is auto-generated by a tool
* 2012 Jochen van Wylick
**/
var Resources = {
  Common: {},
 };
 
Resources.Common.Greetings = { 
 'nl-NL': 'Hallo',
 'en-GB': 'Hello'
 };
