// <auto-generated />
namespace Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddSproc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSproc));
        
        string IMigrationMetadata.Id
        {
            get { return "201502151623467_Add Sproc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
